import {
  IconAbc,
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconApi,
  IconArrowsSplit2,
  IconBadge,
  IconBell,
  IconBolt,
  IconBookmark,
  IconBox,
  IconBracketsContain,
  IconBriefcase,
  IconBulb,
  IconBuilding,
  IconCalendar,
  IconCalendarStats,
  IconCamera,
  IconChartBar,
  IconChartPie,
  IconChecklist,
  IconCircleCheck,
  IconClipboardList,
  IconClock,
  IconCloud,
  IconCode,
  IconCoin,
  IconCreditCard,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDiamond,
  IconDownload,
  IconEye,
  IconFile,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFolder,
  IconFolders,
  IconForms,
  IconGitBranch,
  IconHammer,
  IconHeart,
  IconHexagon,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayoutGrid,
  IconLine,
  IconLink,
  IconLock,
  IconMail,
  IconMapPin,
  IconMessageCircle,
  IconNote,
  IconNotebook,
  IconPackage,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPin,
  IconPlayerPlay,
  IconQuestionMark,
  IconReceipt,
  IconRefresh,
  IconReport,
  IconRocket,
  IconRouteSquare,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShare,
  IconShield,
  IconSquareRounded,
  IconStack2,
  IconStar,
  IconStars,
  IconTarget,
  IconTerminal,
  IconTextSize,
  IconTools,
  IconTopologyComplex,
  IconTrash,
  IconTriangle,
  IconTruck,
  IconTypography,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUsers,
  IconVectorBezier2,
  IconVideo,
  IconWifi,
  IconWorld,
} from '@tabler/icons-react';
import { createElement } from 'react';

import type { ComponentType, SVGProps } from 'react';

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const ICON_LIBRARY = {
  play: IconPlayerPlay,
  settings: IconSettings,
  branch: IconGitBranch,
  success: IconCircleCheck,
  note: IconNote,
  typography: IconTypography,
  input: IconForms,
  database: IconDatabase,
  document: IconFileText,
  subprocess: IconStack2,
  connector: IconRouteSquare,
  rectangle: IconBox,
  roundedRectangle: IconSquareRounded,
  circle: IconCircleCheck,
  ellipse: IconCalendarStats,
  diamond: IconDiamond,
  triangle: IconTriangle,
  hexagon: IconHexagon,
  line: IconLine,
  arrow: IconArrowsSplit2,
  frame: IconBracketsContain,
  title: IconTextSize,
  heading: IconTextSize,
  paragraph: IconTypography,
  label: IconAbc,
  caption: IconTypography,
  callout: IconMessageCircle,
  stickyNote: IconNote,
  comment: IconMessageCircle,
  warning: IconAlertTriangle,
  info: IconInfoCircle,
  checklist: IconChecklist,
  icon: IconStars,
  architecture: IconTopologyComplex,
  journey: IconRouteSquare,
  organization: IconBriefcase,
  pipeline: IconVectorBezier2,
  persona: IconUserCircle,
  home: IconHome,
  mail: IconMail,
  phone: IconPhone,
  cloud: IconCloud,
  server: IconServer,
  api: IconApi,
  lock: IconLock,
  key: IconKey,
  shield: IconShield,
  chartBar: IconChartBar,
  chartPie: IconChartPie,
  report: IconReport,
  users: IconUsers,
  user: IconUser,
  building: IconBuilding,
  mapPin: IconMapPin,
  clock: IconClock,
  calendar: IconCalendar,
  bolt: IconBolt,
  flame: IconFlame,
  heart: IconHeart,
  star: IconStar,
  bookmark: IconBookmark,
  link: IconLink,
  photo: IconPhoto,
  video: IconVideo,
  camera: IconCamera,
  search: IconSearch,
  bell: IconBell,
  inbox: IconInbox,
  send: IconSend,
  rocket: IconRocket,
  coin: IconCoin,
  creditCard: IconCreditCard,
  truck: IconTruck,
  package: IconPackage,
  world: IconWorld,
  wifi: IconWifi,
  deviceDesktop: IconDeviceDesktop,
  deviceMobile: IconDeviceMobile,
  code: IconCode,
  terminal: IconTerminal,
  clipboardList: IconClipboardList,
  notebook: IconNotebook,
  pencil: IconPencil,
  trash: IconTrash,
  refresh: IconRefresh,
  download: IconDownload,
  upload: IconUpload,
  share: IconShare,
  eye: IconEye,
  tools: IconTools,
  hammer: IconHammer,
  bulb: IconBulb,
  flag: IconFlag,
  target: IconTarget,
  questionMark: IconQuestionMark,
  filter: IconFilter,
  adjustments: IconAdjustmentsHorizontal,
  layoutGrid: IconLayoutGrid,
  folders: IconFolders,
  folder: IconFolder,
  file: IconFile,
  receipt: IconReceipt,
  badge: IconBadge,
  pin: IconPin,
} satisfies Record<string, IconComponent>;

export type IconName = keyof typeof ICON_LIBRARY;

export function getIconComponent(iconName?: string): IconComponent {
  if (iconName && iconName in ICON_LIBRARY) {
    return ICON_LIBRARY[iconName as IconName];
  }

  return ICON_LIBRARY.settings;
}

export function renderIcon(
  iconName: string | undefined,
  props: SVGProps<SVGSVGElement>,
) {
  return createElement(getIconComponent(iconName), props);
}
