import {
  IconAbc,
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconApi,
  IconArrowForward,
  IconArrowRightBar,
  IconBadge,
  IconBell,
  IconBolt,
  IconBookmark,
  IconBracketsContain,
  IconBriefcase,
  IconBulb,
  IconBuilding,
  IconCalendar,
  IconCamera,
  IconChartBar,
  IconChartPie,
  IconChecklist,
  IconCircleCheck,
  IconClipboardList,
  IconClock,
  IconCloud,
  IconCode,
  IconCircle,
  IconCoin,
  IconCreditCard,
  IconCylinder,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDiamond,
  IconDownload,
  IconEye,
  IconFile,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFolder,
  IconFolders,
  IconForms,
  IconGitBranch,
  IconHammer,
  IconHeart,
  IconHexagon,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayoutGrid,
  IconLine,
  IconLink,
  IconLock,
  IconMail,
  IconMapPin,
  IconMessageCircle,
  IconNote,
  IconNotebook,
  IconOval,
  IconPackage,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPin,
  IconPlayerPlay,
  IconPlus,
  IconQuestionMark,
  IconReceipt,
  IconRectangle,
  IconRefresh,
  IconReport,
  IconRocket,
  IconRouteSquare,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShare,
  IconShield,
  IconSquareRounded,
  IconStack2,
  IconStar,
  IconStars,
  IconTarget,
  IconTerminal,
  IconTextSize,
  IconTools,
  IconTopologyComplex,
  IconTrash,
  IconTriangle,
  IconTruck,
  IconTypography,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUsers,
  IconVectorBezier2,
  IconVideo,
  IconWifi,
  IconWorld,
} from '@tabler/icons-react';
import { createElement, forwardRef } from 'react';

import type { ComponentType, SVGProps } from 'react';

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

/** Flowchart-style parallelogram — Tabler has no dedicated shape glyph. */
const ParallelogramGlyph = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>(
  function ParallelogramGlyph(props, ref) {
    return createElement(
      'svg',
      {
        ref,
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 24 24',
        fill: 'none',
        stroke: 'currentColor',
        strokeWidth: 2,
        strokeLinecap: 'round',
        strokeLinejoin: 'round',
        ...props,
      },
      createElement('path', {
        /* Same proportions as ShapePrimitiveNode parallelogram (100×100 → 24×24). */
        d: 'M 4 2 L 23 2 L 20 22 L 1 22 Z',
      }),
    );
  },
);

export const ICON_LIBRARY = {
  play: IconPlayerPlay,
  settings: IconSettings,
  branch: IconGitBranch,
  success: IconCircleCheck,
  note: IconNote,
  typography: IconTypography,
  input: IconForms,
  database: IconDatabase,
  document: IconFileText,
  subprocess: IconStack2,
  connector: IconRouteSquare,
  rectangle: IconRectangle,
  roundedRectangle: IconSquareRounded,
  circle: IconCircle,
  ellipse: IconOval,
  diamond: IconDiamond,
  triangle: IconTriangle,
  hexagon: IconHexagon,
  line: IconLine,
  arrow: IconArrowForward,
  arrowRectangle: IconArrowRightBar,
  cylinder: IconCylinder,
  parallelogram: ParallelogramGlyph,
  plus: IconPlus,
  frame: IconBracketsContain,
  title: IconTextSize,
  heading: IconTextSize,
  paragraph: IconTypography,
  label: IconAbc,
  caption: IconTypography,
  callout: IconMessageCircle,
  stickyNote: IconNote,
  comment: IconMessageCircle,
  warning: IconAlertTriangle,
  info: IconInfoCircle,
  checklist: IconChecklist,
  icon: IconStars,
  architecture: IconTopologyComplex,
  journey: IconRouteSquare,
  organization: IconBriefcase,
  pipeline: IconVectorBezier2,
  persona: IconUserCircle,
  home: IconHome,
  mail: IconMail,
  phone: IconPhone,
  cloud: IconCloud,
  server: IconServer,
  api: IconApi,
  lock: IconLock,
  key: IconKey,
  shield: IconShield,
  chartBar: IconChartBar,
  chartPie: IconChartPie,
  report: IconReport,
  users: IconUsers,
  user: IconUser,
  building: IconBuilding,
  mapPin: IconMapPin,
  clock: IconClock,
  calendar: IconCalendar,
  bolt: IconBolt,
  flame: IconFlame,
  heart: IconHeart,
  star: IconStar,
  bookmark: IconBookmark,
  link: IconLink,
  photo: IconPhoto,
  video: IconVideo,
  camera: IconCamera,
  search: IconSearch,
  bell: IconBell,
  inbox: IconInbox,
  send: IconSend,
  rocket: IconRocket,
  coin: IconCoin,
  creditCard: IconCreditCard,
  truck: IconTruck,
  package: IconPackage,
  world: IconWorld,
  wifi: IconWifi,
  deviceDesktop: IconDeviceDesktop,
  deviceMobile: IconDeviceMobile,
  code: IconCode,
  terminal: IconTerminal,
  clipboardList: IconClipboardList,
  notebook: IconNotebook,
  pencil: IconPencil,
  trash: IconTrash,
  refresh: IconRefresh,
  download: IconDownload,
  upload: IconUpload,
  share: IconShare,
  eye: IconEye,
  tools: IconTools,
  hammer: IconHammer,
  bulb: IconBulb,
  flag: IconFlag,
  target: IconTarget,
  questionMark: IconQuestionMark,
  filter: IconFilter,
  adjustments: IconAdjustmentsHorizontal,
  layoutGrid: IconLayoutGrid,
  folders: IconFolders,
  folder: IconFolder,
  file: IconFile,
  receipt: IconReceipt,
  badge: IconBadge,
  pin: IconPin,
} satisfies Record<string, IconComponent>;

export type IconName = keyof typeof ICON_LIBRARY;

export function getIconComponent(iconName?: string): IconComponent {
  if (iconName && iconName in ICON_LIBRARY) {
    return ICON_LIBRARY[iconName as IconName];
  }

  return ICON_LIBRARY.settings;
}

export function renderIcon(
  iconName: string | undefined,
  props: SVGProps<SVGSVGElement>,
) {
  return createElement(getIconComponent(iconName), props);
}
