import type { IconName } from './iconLibrary.config';
import type {
  DiagramNodeKind,
  DiagramNodeStyle,
  DiagramNodeType,
} from '../types/diagram';

export interface NodeTypeDefinition {
  type: DiagramNodeType;
  label: string;
  defaultLabel: string;
  description: string;
  iconName?: IconName;
  kind: DiagramNodeKind;
  connectable?: boolean;
  resizable?: boolean;
  lightweight?: boolean;
  defaultStyle?: DiagramNodeStyle;
  colorClasses: {
    badge: string;
    border: string;
    background: string;
    text: string;
  };
}

export const NODE_TYPE_DEFINITIONS = [
  {
    type: 'start',
    label: 'Start',
    defaultLabel: 'Start',
    description: 'Entry point for a workflow or process.',
    iconName: 'play',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-success-soft text-success-text',
      border: 'border-success/40',
      background: 'bg-success-soft/70',
      text: 'text-success-text',
    },
    defaultStyle: { backgroundColor: 'success-soft', borderColor: 'success' },
  },
  {
    type: 'end',
    label: 'End',
    defaultLabel: 'End',
    description: 'Terminal step or successful completion state.',
    iconName: 'success',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-danger-soft text-danger-text',
      border: 'border-danger/35',
      background: 'bg-danger-soft/75',
      text: 'text-danger-text',
    },
    defaultStyle: { backgroundColor: 'danger-soft', borderColor: 'danger' },
  },
  {
    type: 'process',
    label: 'Process',
    defaultLabel: 'Process',
    description: 'Standard action or transformation step.',
    iconName: 'settings',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-primary-soft text-primary-text',
      border: 'border-primary/35',
      background: 'bg-primary-soft/70',
      text: 'text-primary-text',
    },
    defaultStyle: { backgroundColor: 'primary-soft', borderColor: 'primary' },
  },
  {
    type: 'decision',
    label: 'Decision',
    defaultLabel: 'Decision',
    description: 'Branch logic with yes/no or conditional outcomes.',
    iconName: 'branch',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-warning-soft text-warning-text',
      border: 'border-warning/40',
      background: 'bg-warning-soft/80',
      text: 'text-warning-text',
    },
    defaultStyle: { backgroundColor: 'warning-soft', borderColor: 'warning' },
  },
  {
    type: 'input-output',
    label: 'Input / Output',
    defaultLabel: 'Input / Output',
    description: 'Captures input and output steps in a flow.',
    iconName: 'input',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-primary-soft text-primary-text',
      border: 'border-primary/25',
      background: 'bg-primary-soft/55',
      text: 'text-primary-text',
    },
    defaultStyle: { backgroundColor: 'primary-soft', borderColor: 'primary' },
  },
  {
    type: 'database',
    label: 'Database',
    defaultLabel: 'Database',
    description: 'Persistent storage or system of record.',
    iconName: 'database',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-accent-soft text-accent-text',
      border: 'border-accent/35',
      background: 'bg-accent-soft/70',
      text: 'text-accent-text',
    },
    defaultStyle: { backgroundColor: 'accent-soft', borderColor: 'accent' },
  },
  {
    type: 'document',
    label: 'Document',
    defaultLabel: 'Document',
    description: 'Document, report, or generated artifact.',
    iconName: 'document',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'subprocess',
    label: 'Subprocess',
    defaultLabel: 'Subprocess',
    description: 'Reusable or collapsed process block.',
    iconName: 'subprocess',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-accent-soft text-accent-text',
      border: 'border-accent/35',
      background: 'bg-accent-soft/55',
      text: 'text-accent-text',
    },
    defaultStyle: { backgroundColor: 'accent-soft', borderColor: 'accent' },
  },
  {
    type: 'connector',
    label: 'Connector',
    defaultLabel: 'Connector',
    description: 'Cross-link or jump point between distant blocks.',
    iconName: 'connector',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-surface-hover text-text-muted',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text-muted',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'rectangle',
    label: 'Rectangle',
    defaultLabel: 'Rectangle',
    description: 'Basic rectangular shape with optional text.',
    iconName: 'rectangle',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'rounded-rectangle',
    label: 'Rounded Rectangle',
    defaultLabel: 'Rounded Rectangle',
    description: 'Softer rectangle shape for cards and containers.',
    iconName: 'roundedRectangle',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'circle',
    label: 'Circle',
    defaultLabel: 'Circle',
    description: 'Circular marker or emphasis block.',
    iconName: 'circle',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'ellipse',
    label: 'Ellipse',
    defaultLabel: 'Ellipse',
    description: 'Wide circular shape for emphasis or start/end variants.',
    iconName: 'ellipse',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'diamond',
    label: 'Diamond',
    defaultLabel: 'Diamond',
    description: 'Decision-style shape for branches and checks.',
    iconName: 'diamond',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-warning-soft text-warning-text',
      border: 'border-warning/40',
      background: 'bg-warning-soft/70',
      text: 'text-warning-text',
    },
    defaultStyle: { backgroundColor: 'warning-soft', borderColor: 'warning' },
  },
  {
    type: 'triangle',
    label: 'Triangle',
    defaultLabel: 'Triangle',
    description: 'Directional or warning-oriented shape.',
    iconName: 'triangle',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-warning-soft text-warning-text',
      border: 'border-warning/40',
      background: 'bg-warning-soft/60',
      text: 'text-warning-text',
    },
    defaultStyle: { backgroundColor: 'warning-soft', borderColor: 'warning' },
  },
  {
    type: 'hexagon',
    label: 'Hexagon',
    defaultLabel: 'Hexagon',
    description: 'Structured geometry for infrastructure diagrams.',
    iconName: 'hexagon',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-accent-soft text-accent-text',
      border: 'border-accent/35',
      background: 'bg-accent-soft/60',
      text: 'text-accent-text',
    },
    defaultStyle: { backgroundColor: 'accent-soft', borderColor: 'accent' },
  },
  {
    type: 'line',
    label: 'Line',
    defaultLabel: 'Line',
    description: 'Linear visual separator or guide.',
    iconName: 'line',
    kind: 'shape',
    connectable: false,
    colorClasses: {
      badge: 'bg-surface-hover text-text-muted',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text-muted',
    },
    defaultStyle: { backgroundColor: 'transparent', borderColor: 'border' },
  },
  {
    type: 'arrow',
    label: 'Arrow',
    defaultLabel: 'Arrow',
    description: 'Standalone directional shape with optional text.',
    iconName: 'arrow',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-surface-hover text-text-muted',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text-muted',
    },
    defaultStyle: { backgroundColor: 'transparent', borderColor: 'border' },
  },
  {
    type: 'frame',
    label: 'Container / Frame',
    defaultLabel: 'Frame',
    description: 'Large framing block for sections and swimlanes.',
    iconName: 'frame',
    kind: 'shape',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface-muted', borderColor: 'border' },
  },
  {
    type: 'text',
    label: 'Text Block',
    defaultLabel: '',
    description: 'Lightweight freeform text for annotations and titles.',
    iconName: 'typography',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-transparent text-text-muted',
      border: 'border-transparent',
      background: 'bg-transparent',
      text: 'text-text',
    },
    defaultStyle: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
    },
  },
  {
    type: 'title',
    label: 'Title',
    defaultLabel: 'Diagram title',
    description: 'Large display text for section or board titles.',
    iconName: 'title',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-transparent text-text-muted',
      border: 'border-transparent',
      background: 'bg-transparent',
      text: 'text-text',
    },
    defaultStyle: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      fontSize: 29,
    },
  },
  {
    type: 'heading',
    label: 'Heading',
    defaultLabel: 'Heading',
    description: 'Section heading for cluster context.',
    iconName: 'heading',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-transparent text-text-muted',
      border: 'border-transparent',
      background: 'bg-transparent',
      text: 'text-text',
    },
    defaultStyle: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      fontSize: 22,
    },
  },
  {
    type: 'paragraph',
    label: 'Paragraph',
    defaultLabel: 'Paragraph',
    description: 'Long-form explanatory copy for diagram context.',
    iconName: 'paragraph',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-transparent text-text-muted',
      border: 'border-transparent',
      background: 'bg-transparent',
      text: 'text-text',
    },
    defaultStyle: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
    },
  },
  {
    type: 'label',
    label: 'Label',
    defaultLabel: 'Label',
    description: 'Short label for connectors or containers.',
    iconName: 'label',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-transparent text-text-muted',
      border: 'border-transparent',
      background: 'bg-transparent',
      text: 'text-text',
    },
    defaultStyle: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      fontSize: 16,
    },
  },
  {
    type: 'caption',
    label: 'Caption',
    defaultLabel: 'Caption',
    description: 'Muted support text for details and references.',
    iconName: 'caption',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-transparent text-text-subtle',
      border: 'border-transparent',
      background: 'bg-transparent',
      text: 'text-text-muted',
    },
    defaultStyle: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      fontSize: 14,
    },
  },
  {
    type: 'callout',
    label: 'Callout',
    defaultLabel: 'Callout',
    description: 'Highlighted narrative text for emphasis.',
    iconName: 'callout',
    kind: 'text',
    lightweight: true,
    colorClasses: {
      badge: 'bg-primary-soft text-primary-text',
      border: 'border-primary/25',
      background: 'bg-primary-soft/40',
      text: 'text-primary-text',
    },
    defaultStyle: {
      backgroundColor: 'primary-soft',
      borderColor: 'transparent',
    },
  },
  {
    type: 'note',
    label: 'Note',
    defaultLabel: 'Note',
    description: 'General purpose note or annotation.',
    iconName: 'note',
    kind: 'note',
    colorClasses: {
      badge: 'bg-surface-hover text-text-muted',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text-muted',
    },
    defaultStyle: { backgroundColor: 'surface-muted', borderColor: 'border' },
  },
  {
    type: 'sticky-note',
    label: 'Sticky Note',
    defaultLabel: '',
    description: 'Pinned annotation with a lightweight note look.',
    iconName: 'stickyNote',
    kind: 'note',
    colorClasses: {
      badge: 'bg-warning-soft text-warning-text',
      border: 'border-warning/35',
      background: 'bg-warning-soft/70',
      text: 'text-warning-text',
    },
    defaultStyle: { backgroundColor: 'warning-soft', borderColor: 'warning' },
  },
  {
    type: 'comment',
    label: 'Comment',
    defaultLabel: 'Comment',
    description: 'Conversation-oriented annotation block.',
    iconName: 'comment',
    kind: 'note',
    colorClasses: {
      badge: 'bg-accent-soft text-accent-text',
      border: 'border-accent/35',
      background: 'bg-accent-soft/55',
      text: 'text-accent-text',
    },
    defaultStyle: { backgroundColor: 'accent-soft', borderColor: 'accent' },
  },
  {
    type: 'warning',
    label: 'Warning',
    defaultLabel: 'Warning',
    description: 'Risk or concern callout block.',
    iconName: 'warning',
    kind: 'note',
    colorClasses: {
      badge: 'bg-warning-soft text-warning-text',
      border: 'border-warning/40',
      background: 'bg-warning-soft/65',
      text: 'text-warning-text',
    },
    defaultStyle: { backgroundColor: 'warning-soft', borderColor: 'warning' },
  },
  {
    type: 'info',
    label: 'Info',
    defaultLabel: 'Info',
    description: 'Informational note or explainer block.',
    iconName: 'info',
    kind: 'note',
    colorClasses: {
      badge: 'bg-primary-soft text-primary-text',
      border: 'border-primary/35',
      background: 'bg-primary-soft/60',
      text: 'text-primary-text',
    },
    defaultStyle: { backgroundColor: 'primary-soft', borderColor: 'primary' },
  },
  {
    type: 'checklist',
    label: 'Checklist',
    defaultLabel: 'Checklist',
    description: 'Task-oriented note block with progress context.',
    iconName: 'checklist',
    kind: 'note',
    colorClasses: {
      badge: 'bg-success-soft text-success-text',
      border: 'border-success/35',
      background: 'bg-success-soft/55',
      text: 'text-success-text',
    },
    defaultStyle: { backgroundColor: 'success-soft', borderColor: 'success' },
  },
  {
    type: 'icon',
    label: 'Icon',
    defaultLabel: 'Icon label',
    description: 'Standalone icon block with optional supporting text.',
    iconName: 'icon',
    kind: 'icon',
    connectable: false,
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'group',
    label: 'Group',
    defaultLabel: 'Group Container',
    description: 'Container for moving selected nodes together.',
    iconName: 'frame',
    kind: 'group',
    colorClasses: {
      badge: 'bg-accent-soft text-accent-text',
      border: 'border-accent/35',
      background: 'bg-accent-soft/70',
      text: 'text-accent-text',
    },
    defaultStyle: { backgroundColor: 'accent-soft', borderColor: 'accent' },
  },
  {
    type: 'custom-input',
    label: 'Input',
    defaultLabel: 'Input',
    description: 'Editable input node with label and value.',
    iconName: 'input',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'counter',
    label: 'Counter',
    defaultLabel: 'Counter',
    description: 'Interactive counter/status node.',
    iconName: 'badge',
    kind: 'flow',
    colorClasses: {
      badge: 'bg-primary-soft text-primary-text',
      border: 'border-primary/35',
      background: 'bg-primary-soft/65',
      text: 'text-primary-text',
    },
    defaultStyle: { backgroundColor: 'primary-soft', borderColor: 'primary' },
  },
  {
    type: 'circle-compact',
    label: 'Circle',
    defaultLabel: 'Circle',
    description: 'Compact circular node for tight diagrams.',
    iconName: 'circle',
    kind: 'shape',
    resizable: true,
    colorClasses: {
      badge: 'bg-accent-soft text-accent-text',
      border: 'border-accent/35',
      background: 'bg-accent-soft/55',
      text: 'text-accent-text',
    },
    defaultStyle: {
      backgroundColor: 'accent-soft',
      borderColor: 'accent',
      width: 160,
      height: 160,
    },
  },
  {
    type: 'svg-shape',
    label: 'SVG Shape',
    defaultLabel: 'SVG Shape',
    description: 'SVG-based visual node with configurable shape.',
    iconName: 'layoutGrid',
    kind: 'shape',
    resizable: true,
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'architecture',
    label: 'Architecture',
    defaultLabel: 'Service',
    description: 'Icon + title + subtitle + status for system design.',
    iconName: 'architecture',
    kind: 'flow',
    resizable: true,
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'toolbar',
    label: 'Toolbar Node',
    defaultLabel: 'Toolbar Node',
    description: 'Node with quick actions shown on selection.',
    iconName: 'tools',
    kind: 'flow',
    resizable: true,
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-surface-muted',
      text: 'text-text',
    },
    defaultStyle: { backgroundColor: 'surface', borderColor: 'border' },
  },
  {
    type: 'shape-circle',
    label: 'Circle',
    defaultLabel: 'Circle',
    description: 'Primitive circle shape (no card container).',
    iconName: 'circle',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 160,
      height: 160,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-rectangle',
    label: 'Rectangle',
    defaultLabel: 'Rectangle',
    description: 'Primitive rectangle shape (no card container).',
    iconName: 'rectangle',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 220,
      height: 140,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-rounded-rectangle',
    label: 'Rounded Rectangle',
    defaultLabel: 'Rounded',
    description: 'Primitive rounded rectangle shape (no card container).',
    iconName: 'roundedRectangle',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 220,
      height: 140,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-diamond',
    label: 'Diamond',
    defaultLabel: 'Diamond',
    description: 'Primitive diamond shape (no card container).',
    iconName: 'diamond',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 190,
      height: 160,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-hexagon',
    label: 'Hexagon',
    defaultLabel: 'Hexagon',
    description: 'Primitive hexagon shape (no card container).',
    iconName: 'hexagon',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 210,
      height: 150,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-triangle',
    label: 'Triangle',
    defaultLabel: 'Triangle',
    description: 'Primitive triangle shape (no card container).',
    iconName: 'triangle',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 190,
      height: 160,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-parallelogram',
    label: 'Parallelogram',
    defaultLabel: 'IO',
    description: 'Primitive parallelogram shape (no card container).',
    iconName: 'input',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 230,
      height: 140,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-cylinder',
    label: 'Cylinder',
    defaultLabel: 'DB',
    description: 'Primitive cylinder shape (no card container).',
    iconName: 'database',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 220,
      height: 170,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-arrow-rectangle',
    label: 'Arrow Rectangle',
    defaultLabel: 'Next',
    description: 'Primitive arrow-rectangle shape (no card container).',
    iconName: 'arrow',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 250,
      height: 120,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-plus',
    label: 'Plus',
    defaultLabel: '',
    description: 'Primitive plus shape (no card container).',
    iconName: 'icon',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    connectable: false,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 150,
      height: 150,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
  {
    type: 'shape-cloud',
    label: 'Cloud',
    defaultLabel: 'Cloud',
    description: 'Primitive cloud shape (future-ready).',
    iconName: 'cloud',
    kind: 'shape',
    resizable: true,
    lightweight: true,
    defaultStyle: {
      fillColor: 'transparent',
      borderColor: 'border',
      width: 240,
      height: 160,
    },
    colorClasses: {
      badge: 'bg-surface-hover text-text',
      border: 'border-border-strong',
      background: 'bg-transparent',
      text: 'text-text',
    },
  },
] satisfies NodeTypeDefinition[];

export const NODE_TYPE_MAP = Object.fromEntries(
  NODE_TYPE_DEFINITIONS.map((definition) => [definition.type, definition]),
) as Record<DiagramNodeType, NodeTypeDefinition>;
